#include<iostream>
using namespace std;
int main(){
	cout<<"1"<<endl;
	cout<<"2"<<endl;
	cout<<"3"<<endl;
	cout<<"4"<<endl;
	cout<<"5"<<endl;
	cout<<"6"<<endl;
	cout<<"7"<<endl;
	cout<<"8"<<endl;
	cout<<"9"<<endl;
	cout<<"10"<<endl;
	cout<<"11"<<endl;
	cout<<"12"<<endl;
	cout<<"13"<<endl;
	cout<<"14"<<endl;
	cout<<"15"<<endl;
	cout<<"16"<<endl;
	cout<<"17"<<endl;
	cout<<"18"<<endl;
	cout<<"19"<<endl;
	cout<<"20"<<endl;
	cout<<"21"<<endl;
	cout<<"22"<<endl;
	cout<<"23"<<endl;
	cout<<"24"<<endl;
	cout<<"25"<<endl;
	cout<<"26"<<endl;
	cout<<"27"<<endl;
	cout<<"28"<<endl;
	cout<<"29"<<endl;
	cout<<"30"<<endl;
	cout<<"31"<<endl;
	cout<<"32"<<endl;
	cout<<"33"<<endl;
	cout<<"34"<<endl;
	return 0;
}